### PR TITLE
Remove Charter Font

### PR DESCRIPTION
**Pull request by jaywilliams**
The front rendering looks horrible on Firefox (OpenBSD)

image

### CODE REVIEW

**Comment by anoxic** [comment]
Do you have anti-aliasing enabled? Maybe try tweaking the `text-rendering` attribute before removing this altogether. I use the font on macOS and I think it looks great, although the anti-aliasing is nice. Do you have a suitable alternative? I really would like to keep a neutral serif face for the titling. Lucida Bright is nice, but only available on Windows. Georgia is OK but is worse than Charter at larger sizes, and not included in base for open source systems. But a clean stack is nice.

If I wanted to go with a commercial font, [FF Yoga](https://www.fontshop.com/families/ff-yoga) is the general flavor I'm going for. But I really want to go without adding any external assets to the base CSS. Maybe I will add a "css override" for theming later that will allow more customization.

If tweaking some attributes doesn't help, I would prefer you find a font that comes in base that renders better for you to put earlier in the font stack.

**Comment by jaywilliams** [comment]
Changing the `text-rendering` attribute made no difference. What puzzles me is I don't even have the Charter font installed (as far as I can tell). So it should fall back, and the fallback fonts (Georgia, serif) render perfectly with anti-aliasing, as does all of the other text on the page.

**Comment by anoxic** [comment]
I just added Liberation, Luxi, and Century Schoolbook at the front of the font stack on the community wiki. How does that look to you? I'm not sure what vector fonts you have available on a default x11 install. I think Liberation may come default now but I'm not sure. Schoolbook is available as a part of the the official x11 ghost script fonts package.

**Comment by jaywilliams** [comment]
Perfect, I have all of those; and they all render as smooth vector fonts.

**Pull request closed without merging**
